### ISSUE TITLE
Transfer of ownership

### ISSUE THREAD

**Issue by mullermp** [RyanJarv/aws-sdk-sts#1]
Hi @RyanJarv , I got a ticket about this issue internally. Thanks for raising the issue to us. Unfortunately RubyGems.org does not support namespacing of gems, so technically anyone can reserve `aws-sdk-foo` gems. In this case, STS service is already established but no such V3 gem (aws-sdk-sts) existed because it was designed to live in aws-sdk-core.

With your permission, we will own this gem and make it an alias of aws-sdk-core (since STS is included in core). This would work the same way as aws-sdk-sso. It would not raise an error. It would be published as version 1.0.0 in line with the other SDK gem versions.

https://github.com/aws/aws-sdk-ruby/pull/2441

**Comment by RyanJarv** [comment]
Yeah, tbh I think that one's on rubygems, they really should support that.

I'm not sure how transferring works with that, I can look into it a later when I have time or if you know how just let me know what to do.

**Comment by RyanJarv** [comment]
Ok looks like it's pretty simple, I just need a email/handle to add an owner to the repo.

If you could have sec respond via the original open issue (aws-security@ email) on who to add that would be helpful. 

<img width="434" alt="Screen Shot 2020-12-01 at 1 49 57 PM" src="https://user-images.githubusercontent.com/4079939/100789476-1dc1e480-33dc-11eb-8956-957e0e36e5d1.png">

**Comment by RyanJarv** [comment]
If you want me to transfer this repo as well just let me know the org it should go under.

Edit: Or I guess you can fork it, same difference.

**Comment by mullermp** [comment]
I'm not on the email thread that you have open - they created a separate tracking ticket this morning. I figured it's easier to reach out to you directly.

For transfer, in RubyGems you should be able to set the owner to awscloud

https://rubygems.org/profiles/awscloud

**Comment by mullermp** [comment]
No need to transfer the repo, you can close it down. We will put the aliased gem under the aws-sdk-ruby official repo.

**Comment by mullermp** [comment]
That change is here: https://github.com/aws/aws-sdk-ruby/pull/2441

**Comment by RyanJarv** [comment]
Oh ok gotcha. Do you mind pinging sec to have them respond to the email chain, just want to make sure I have the ok from them first.

-- 
  Ryan
  ryan_gerstenkorn@fastmail.fm

**Comment by mullermp** [comment]
Sure. I've updated the ticket and haven't heard back from them.

**Comment by mullermp** [comment]
Did you receive an email response yet?

**Comment by RyanJarv** [comment]
I did, I should be able to do this shortly.

-- 
  Ryan
  ryan_gerstenkorn@fastmail.fm

**Comment by RyanJarv** [comment]
Well I guess I should say later today at the latest. Is there a time that would work best for this?

-- 
  Ryan
  ryan_gerstenkorn@fastmail.fm

**Comment by RyanJarv** [comment]
Do you have a way I can DM you to coordinate on this? Hate to deregister it when you busy with something else. Maybe slack, Twitter or just SMS?

**Comment by mullermp** [comment]
You should be able to set the gem's owner to awscloud in Rubygems.org and then you can close down the Github repo :D I think those are all the actions you need to do and we can take it from there. https://rubygems.org/profiles/awscloud

**Comment by RyanJarv** [comment]
Ah ok perfect, that will work. Will do that in the next half hour.

-- 
  Ryan
  ryan_gerstenkorn@fastmail.fm

**Comment by RyanJarv** [comment]
Added https://rubygems.org/profiles/awscloud to the owners, I'll go ahead and delete my self once it's accepted. Alternatively go ahead and do that for me if it allows you to.

**Comment by mullermp** [comment]
Accepted, and removed you as owner. Thanks for bringing this to our attention. We will release a version 1.0.0 aliases to aws-sdk-core.
